# Site settings
title: Archie's personal blog
email: chungphan78@gmail.com
description: Tech blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chungpt78.github.io/index.html" # the base hostname & protocol for your site

# Paginate
#gems: [jekyll-paginate]
# Number of post on per page.
#paginate: 10
#paginate_path: "page:num"


# Build settings
# markdown
#highlighter: pygments
# markdown compile
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
# type of link for post on blog
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# Information
author:
  name: Archie Phan
  email: chungphan78@gmail.com
  link: http://chungpt78.github.io/
  facebook: http://facebook.com/chungphan78
  facebook_username: chungphan
  github: https://github.com/chungpt78
  github_username: chungphan


locals:
  tags: tags
  about: about
  active: tech
subscribe_rss: /pages/atom.xml

# Avatar
avatar: /assets/image/avatar.jpg
# CSS
css: /assets/css/
# Javascript
js: /assets/js/
# Images
image: /assets/image/

# disqus setting
disqus:
  shortname: chungphan

theme: jekyll-theme-cayman